packages:
  - "packages/*"
  - "workflows"
allowBuilds:
  '@embedded-postgres/linux-arm64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@fission-ai/openspec': true
  esbuild: true
  protobufjs: true
patchedDependencies:
  fetch-blob@4.0.0: patches/fetch-blob@4.0.0.patch
  quickjs-wasi@2.2.0: patches/quickjs-wasi@2.2.0.patch
