workflow_engine:
  TF_VAR_oauth2_client_secret: github/workflow_engine_app_client_secret
  TF_VAR_oauth2_client_id: github/workflow_engine_app_client_id
  TF_VAR_upcloud_token: upcloud/token
  UPCLOUD_TOKEN: upcloud/token
  TF_VAR_dynu_api_key: dynu/api_key

  # tofu state access
  TF_VAR_state_passphrase: tofu/passphrase
  AWS_SECRET_ACCESS_KEY: tofu/secret_access_key
  AWS_ACCESS_KEY_ID: tofu/access_key_id