import { constants } from "node:http2";
import type { ContentfulStatusCode } from "hono/utils/http-status";

const MS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

const FIVE = 5;
const SEVEN = 7;
const TEN = 10;

const SIXTY_SECONDS_MS = SECONDS_PER_MINUTE * MS_PER_SECOND;
const FIVE_MINUTES_MS = FIVE * SECONDS_PER_MINUTE * MS_PER_SECOND;
const TEN_MINUTES_MS = TEN * SECONDS_PER_MINUTE * MS_PER_SECOND;
const SEVEN_DAYS_MS =
	SEVEN * HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MS_PER_SECOND;

const FIVE_MINUTES_SECONDS = FIVE_MINUTES_MS / MS_PER_SECOND;
const SIXTY_SECONDS = SIXTY_SECONDS_MS / MS_PER_SECOND;
const SEVEN_DAYS_SECONDS = SEVEN_DAYS_MS / MS_PER_SECOND;

const SESSION_COOKIE = "session";
const STATE_COOKIE = "auth_state";
const FLASH_COOKIE = "auth_flash";

const LOGIN_PATH = "/login";

const HTTP_UNAUTHORIZED =
	constants.HTTP_STATUS_UNAUTHORIZED as ContentfulStatusCode;
const HTTP_BAD_REQUEST =
	constants.HTTP_STATUS_BAD_REQUEST as ContentfulStatusCode;
const HTTP_BAD_GATEWAY =
	constants.HTTP_STATUS_BAD_GATEWAY as ContentfulStatusCode;
const HTTP_METHOD_NOT_ALLOWED =
	constants.HTTP_STATUS_METHOD_NOT_ALLOWED as ContentfulStatusCode;

export {
	FIVE_MINUTES_MS,
	FIVE_MINUTES_SECONDS,
	FLASH_COOKIE,
	HTTP_BAD_GATEWAY,
	HTTP_BAD_REQUEST,
	HTTP_METHOD_NOT_ALLOWED,
	HTTP_UNAUTHORIZED,
	LOGIN_PATH,
	MS_PER_SECOND,
	SESSION_COOKIE,
	SEVEN_DAYS_MS,
	SEVEN_DAYS_SECONDS,
	SIXTY_SECONDS,
	SIXTY_SECONDS_MS,
	STATE_COOKIE,
	TEN_MINUTES_MS,
};
