terraform {
  # Pin exact patch — operator local + CI must match, otherwise
  # `tofu init` adds version-specific h1: hashes to .terraform.lock.hcl
  # and the lockfile gate (`git diff --exit-code` in ci.yml) flaps on
  # every drift. CI pins the same value via setup-opentofu's tofu_version
  # in .github/workflows/{ci,plan-infra}.yml. Bump deliberately, with a
  # matching CI bump in the same PR.
  required_version = "1.11.6"

  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "~> 2.50"
    }
    restapi = {
      source  = "Mastercard/restapi"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  # Scaleway Object Storage is S3-compatible. Bucket is pre-created out-of-band.
  backend "s3" {
    bucket                      = "tofu-states"
    key                         = "vps"
    endpoints                   = { s3 = "https://s3.fr-par.scw.cloud" }
    region                      = "fr-par"
    use_lockfile                = true
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_s3_checksum            = true
    skip_requesting_account_id  = true
  }

  encryption {
    key_provider "pbkdf2" "state" {
      passphrase = var.state_passphrase
    }
    method "aes_gcm" "state" {
      keys = key_provider.pbkdf2.state
    }
    state {
      method   = method.aes_gcm.state
      enforced = true
    }
  }
}

provider "scaleway" {
  region          = var.scaleway_region
  zone            = var.scaleway_zone
  project_id      = var.scaleway_project_id
  organization_id = var.scaleway_organization_id
}

provider "restapi" {
  uri                  = "https://api.dynu.com/v2"
  write_returns_object = true
  headers = {
    accept       = "application/json"
    Content-Type = "application/json"
    API-Key      = var.dynu_api_key
  }
}

# Public IPv4 — survives stop/start cycles, so DNS records remain valid even
# if the instance is replaced.
resource "scaleway_instance_ip" "vps" {
  type = "routed_ipv4"
}

# Inbound traffic policy. Default deny everything; allow only HTTP, HTTPS, and
# the configured SSH port. Outbound traffic is unrestricted.
resource "scaleway_instance_security_group" "vps" {
  name                    = "wfe-vps"
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    action = "accept"
    port   = 80
  }
  inbound_rule {
    action = "accept"
    port   = 443
  }
  inbound_rule {
    action = "accept"
    port   = var.ssh_port
  }
}

# SSH keypair for the `deploy` user. Generated by tofu on first apply and
# preserved across applies (state-tracked). The private key lives only in
# tofu state at rest (AES-GCM-encrypted via the `encryption {}` block);
# there is no off-host operator copy. Emergency operator access:
# `tofu output -raw deploy_ssh_private_key`. Rotation:
# `tofu taint tls_private_key.deploy && tofu apply` — the new public key
# flips the cloud-init bootstrap hash → VPS replacement (rsync-restore
# ritual per docs/infrastructure.md applies).
resource "tls_private_key" "deploy" {
  algorithm = "ED25519"
}

# Hash of the cloud-init bootstrap content. The Scaleway provider treats
# `scaleway_instance_server.user_data` as API-mutable, so editing the
# template would update the metadata field on the existing box without
# re-executing cloud-init (which runs only at first boot). Without an
# explicit replace trigger, edits to the bootstrap minimum (deploy SSH
# key, sshd hardening, sudoers, ssh_port) silently sit in user_data
# without taking effect. This terraform_data captures the rendered
# content's sha256; the lifecycle rule on `scaleway_instance_server.vps`
# below replaces the VPS when this hash flips.
resource "terraform_data" "cloud_init_bootstrap" {
  input = sha256(templatefile("${path.module}/cloud-init.yaml", {
    ssh_port               = var.ssh_port
    deploy_ssh_public_key  = trimspace(tls_private_key.deploy.public_key_openssh)
    sshd_hardening_content = "      ${replace(templatefile("${path.module}/files/sshd_hardening.conf.tmpl", { ssh_port = var.ssh_port }), "\n", "\n      ")}"
    sudoers_deploy_content = "      ${replace(file("${path.module}/files/sudoers_deploy"), "\n", "\n      ")}"
  }))
}

resource "scaleway_instance_server" "vps" {
  name              = "wfe"
  type              = var.instance_type
  image             = var.instance_image
  ip_id             = scaleway_instance_ip.vps.id
  security_group_id = scaleway_instance_security_group.vps.id

  # Replace the VPS when the cloud-init bootstrap content changes — see
  # `terraform_data.cloud_init_bootstrap` rationale above. The bootstrap
  # surface is small (deploy user + ssh key + sshd hardening + sudoers
  # + ufw baseline + FORWARD policy), so this fires rarely; routine
  # host-config edits flow through the in-place convergence mechanism
  # (host.tf + null_resources below) which does NOT replace the VPS.
  lifecycle {
    replace_triggered_by = [terraform_data.cloud_init_bootstrap]
  }

  # Local SSD root volume (10 GB, included with STARDUST1-S, free).
  # Local SSDs die on instance replacement; the rsync-and-restore ritual
  # in docs/infrastructure.md covers preserving `/srv` data across the
  # rare bootstrap-content rebuild.
  root_volume {
    size_in_gb            = 10
    volume_type           = "l_ssd"
    delete_on_termination = true
  }

  user_data = {
    cloud-init = templatefile("${path.module}/cloud-init.yaml", {
      ssh_port              = var.ssh_port
      deploy_ssh_public_key = trimspace(tls_private_key.deploy.public_key_openssh)
      # Single source of truth for sshd hardening + sudoers content: the
      # same files the in-place convergence (host.tf) manages. Strings are
      # pre-indented to 6 spaces (matching cloud-init's `content: |` block
      # level) because tofu's `indent()` only prefixes lines 2+, leaving
      # line 1 unindented and breaking the YAML literal block.
      sshd_hardening_content = "      ${replace(templatefile("${path.module}/files/sshd_hardening.conf.tmpl", { ssh_port = var.ssh_port }), "\n", "\n      ")}"
      sudoers_deploy_content = "      ${replace(file("${path.module}/files/sudoers_deploy"), "\n", "\n      ")}"
    })
  }
}

# Single source of truth for per-env configuration. Every other resource
# (apps.tf, caddy.tf, dns.tf, outputs.tf) iterates this map — adding a third
# env is a single new key here plus whatever GHA secrets it needs.
locals {
  envs = {
    prod = {
      domain             = "workflow-engine.webredirect.org"
      dns_node           = ""
      port               = 8081
      image_ref          = "${var.app_image}:release"
      data_dir           = "/srv/wfe/prod"
      memory_max         = "350M"
      runtime_user       = "wfe-prod"
      gh_oauth_client_id = var.gh_oauth_client_id_prod
      gh_oauth_secret    = var.gh_oauth_client_secret_prod
      auth_allow         = "github:user:stefanhoelzl,github:user:mrh1997,github:org:baltech-ag,github:org:sharepad-de"
    }
    staging = {
      domain             = "staging.workflow-engine.webredirect.org"
      dns_node           = "staging"
      port               = 8082
      image_ref          = "${var.app_image}:main"
      data_dir           = "/srv/wfe/staging"
      memory_max         = "350M"
      runtime_user       = "wfe-staging"
      gh_oauth_client_id = var.gh_oauth_client_id_staging
      gh_oauth_secret    = var.gh_oauth_client_secret_staging
      auth_allow         = "github:user:stefanhoelzl"
    }
  }

  # SSH connection block shared by every provisioner.
  ssh = {
    type        = "ssh"
    host        = scaleway_instance_ip.vps.address
    user        = "deploy"
    port        = var.ssh_port
    private_key = tls_private_key.deploy.private_key_openssh
    timeout     = "30s"
  }
}

# Block until cloud-init has finished. Every other provisioner depends on this
# so we never race the bootstrap.
resource "null_resource" "wait_cloud_init" {
  triggers = merge(local.ssh_triggers, {
    server_id = scaleway_instance_server.vps.id
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    # cloud-init exits 2 on any recoverable error (deprecation warnings,
    # Scaleway-Debian-specific module noise), so treat 0 and 2 as success
    # and assert the textual status is `done`.
    inline = [
      "cloud-init status --wait || [ $? -eq 2 ]",
      "cloud-init status | grep -q '^status: done$'",
    ]
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# In-place convergence mechanism
#
# Stage order: users → dirs → packages → files_pre → exec → ufw → files_post
# Each stage's null_resource uses for_each over a typed map; replacement on
# content/spec hash flip → destroy provisioner of OLD instance runs, then
# create provisioner of NEW writes the new content + on-change hook fires.
#
# All resources share `local.ssh` for the SSH connection.
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # Merge per-area file maps. Each entry's `stage` key (`pre` or `post`)
  # selects which null_resource (managed_file_pre / managed_file_post) owns it.
  managed_files = merge(
    local.managed_files_host,
    local.managed_files_apps,
    local.managed_files_caddy,
  )

  managed_files_pre  = { for k, v in local.managed_files : k => v if v.stage == "pre" }
  managed_files_post = { for k, v in local.managed_files : k => v if v.stage == "post" }

  # SSH connection details that each convergence resource embeds in its
  # `triggers` map. Destroy-time provisioners can only reference attributes
  # of their own resource via `self.*`, so the connection block of any
  # resource with a destroy provisioner must read SSH parameters from
  # `self.triggers.*` rather than `local.ssh.*`. Keeping the values in
  # state is fine — the state file is AES-GCM-encrypted at rest via the
  # `encryption {}` block.
  ssh_triggers = {
    ssh_host        = local.ssh.host
    ssh_user        = local.ssh.user
    ssh_port        = tostring(local.ssh.port)
    ssh_private_key = local.ssh.private_key
  }
}

# Stage 1: per-tenant container-runtime users.
# Sudoers (/etc/sudoers.d/deploy) is owned by cloud-init, NOT by this
# convergence mechanism — managing the sudoers file in-place created a
# destroy/create race (old destroy provisioner could delete the file
# after the new create wrote it, leaving the box with no NOPASSWD rules
# and no way to self-recover). Edits to the sudoers list now trigger
# VPS replacement, which is acceptable at the expected edit frequency
# (~1/year — adding a new converge primitive is rare).
resource "null_resource" "managed_user" {
  for_each   = local.managed_users
  depends_on = [null_resource.wait_cloud_init]

  triggers = merge(local.ssh_triggers, {
    instance = null_resource.wait_cloud_init.id
    spec     = "${each.value.shell}|${each.value.subuid}"
    user     = each.key
  })

  lifecycle {
    precondition {
      # Subuid ranges across managed_users must not overlap. For each entry,
      # count how many OTHER entries overlap with this one — must be zero.
      # Two ranges [a1,b1] and [a2,b2] overlap iff max(a1,a2) <= min(b1,b2).
      condition = length([
        for k, v in local.managed_users :
        k if k != each.key && (
          tonumber(split("-", v.subuid)[0]) <= tonumber(split("-", each.value.subuid)[1]) &&
          tonumber(split("-", v.subuid)[1]) >= tonumber(split("-", each.value.subuid)[0])
        )
      ]) == 0
      error_message = "Subuid range for managed user '${each.key}' (${each.value.subuid}) overlaps another entry. Ranges must be non-overlapping; each entry needs a unique 65536-id slice."
    }
  }

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    inline = [
      # Idempotent create. useradd fails if user exists, so guard.
      # --create-home so /home/<user> exists for the user-mode Quadlet
      # drop-in (managed via managed_dirs and managed_files in later stages).
      # Note: useradd auto-allocates subuids/subgids per /etc/login.defs.
      # We deliberately overwrite those with our explicit ranges via the
      # managed_files entries for /etc/subuid + /etc/subgid (rendered from
      # local.managed_users) — usermod --add-subuids would STACK on top of
      # the auto-allocated range, leaving each user with two ranges and
      # opening cross-tenant overlaps.
      "id ${each.key} >/dev/null 2>&1 || sudo /usr/sbin/useradd --create-home --shell ${each.value.shell} ${each.key}",
      # Reconcile shell + lock state.
      "sudo /usr/sbin/usermod --shell ${each.value.shell} --lock ${each.key}",
      # Enable lingering so the user's systemd starts at boot — required
      # for user-mode Quadlets to be picked up by the Quadlet generator
      # without an interactive login. Idempotent.
      "sudo /usr/bin/loginctl enable-linger ${each.key}",
      # Wait for /run/user/<UID>/bus to exist (user systemd up).
      "for i in $(seq 1 10); do test -S /run/user/$(id -u ${each.key})/bus && break; sleep 1; done",
    ]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    # Disable linger first so the user's systemd stops, then userdel.
    # userdel --remove fails if processes are still running — that's the
    # desired fail-loud behavior (operator must remove the tenant's
    # Quadlet first; tofu destroys dependents in reverse-dependency order
    # so this should not happen for clean tenant removal).
    inline = [
      "sudo /usr/bin/loginctl disable-linger ${self.triggers.user} 2>/dev/null || true",
      "sudo /usr/sbin/userdel --remove ${self.triggers.user}",
    ]
  }
}

# Stage 2: directories. install -d is idempotent and creates parents.
resource "null_resource" "managed_dir" {
  for_each = local.managed_dirs
  depends_on = [
    null_resource.wait_cloud_init,
    null_resource.managed_user,
  ]

  triggers = merge(local.ssh_triggers, {
    instance = null_resource.wait_cloud_init.id
    spec     = "${each.value.mode}|${each.value.owner}|${each.value.group}"
    path     = each.key
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo /usr/bin/install -d -m ${each.value.mode} -o ${each.value.owner} -g ${each.value.group} ${each.key}",
    ]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    # rmdir fails on non-empty dirs — protects against accidental data
    # loss if a /srv/* dir is removed from the map while data exists.
    inline = ["sudo /usr/bin/rm -df ${self.triggers.path} 2>/dev/null || true"]
  }
}

# Stage 3: apt packages. List-based; replaces when the joined-sorted hash
# changes. No destroy provisioner — removing a package from the list does
# NOT auto-purge (apt state is shared with the host's own history).
resource "null_resource" "managed_packages" {
  depends_on = [null_resource.wait_cloud_init]

  triggers = merge(local.ssh_triggers, {
    instance = null_resource.wait_cloud_init.id
    list     = sha256(join(",", sort(local.managed_packages)))
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo /usr/bin/apt-get update -qq",
      "sudo /usr/bin/apt-get install -y ${join(" ", local.managed_packages)}",
    ]
  }
}

# Stage 4: pre-stage managed files (host-level configs + env files +
# Caddyfile). Pre-stage runs before exec/ufw/files_post.
resource "null_resource" "managed_file_pre" {
  for_each = local.managed_files_pre
  depends_on = [
    null_resource.managed_dir,
    null_resource.managed_packages,
  ]

  triggers = merge(local.ssh_triggers, {
    instance   = null_resource.wait_cloud_init.id
    content    = sha256(each.value.content)
    spec       = "${each.value.path}|${each.value.mode}|${each.value.owner}|${each.value.group}|${each.value.sudo}"
    on_destroy = each.value.on_destroy
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "file" {
    content     = each.value.content
    destination = "/tmp/mf-${each.key}"
  }

  provisioner "remote-exec" {
    inline = [
      "${each.value.sudo ? "sudo /usr/bin/" : ""}install -m ${each.value.mode} -o ${each.value.owner} -g ${each.value.group} /tmp/mf-${each.key} ${each.value.path}",
      "rm -f /tmp/mf-${each.key}",
      each.value.on_change != "" ? each.value.on_change : ":",
    ]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    inline     = [self.triggers.on_destroy != "" ? self.triggers.on_destroy : ":"]
  }
}

# Stage 5: imperative one-shots (subuid is folded into managed_user's
# create; what remains is swapfile + service enables).
resource "null_resource" "managed_exec" {
  for_each   = local.managed_exec
  depends_on = [null_resource.managed_file_pre]

  triggers = merge(local.ssh_triggers, {
    instance   = null_resource.wait_cloud_init.id
    change_key = each.value.change_key
    on_destroy = each.value.on_destroy
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    inline = [each.value.on_create]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    inline     = [self.triggers.on_destroy != "" ? self.triggers.on_destroy : ":"]
  }
}

# Stage 6: app-side firewall rules. Additive on top of cloud-init's
# ssh-only baseline.
resource "null_resource" "managed_ufw" {
  for_each   = local.managed_ufw
  depends_on = [null_resource.managed_exec]

  triggers = merge(local.ssh_triggers, {
    instance = null_resource.wait_cloud_init.id
    rule     = "${each.value.port}/${each.value.proto}"
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "remote-exec" {
    inline = ["sudo /usr/sbin/ufw allow ${each.value.port}/${each.value.proto}"]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    inline     = ["sudo /usr/sbin/ufw delete allow ${self.triggers.rule}"]
  }
}

# Stage 7: post-stage managed files (Quadlet definitions). Post-stage
# runs after pre-stage files exist (env files, Caddyfile) AND after
# managed_exec (services enabled, swap on) AND after managed_ufw
# (80/443 open before Caddy starts ACME).
resource "null_resource" "managed_file_post" {
  for_each = local.managed_files_post
  depends_on = [
    null_resource.managed_file_pre,
    null_resource.managed_exec,
    null_resource.managed_ufw,
  ]

  triggers = merge(local.ssh_triggers, {
    instance   = null_resource.wait_cloud_init.id
    content    = sha256(each.value.content)
    spec       = "${each.value.path}|${each.value.mode}|${each.value.owner}|${each.value.group}|${each.value.sudo}"
    on_destroy = each.value.on_destroy
  })

  connection {
    type        = "ssh"
    host        = self.triggers.ssh_host
    user        = self.triggers.ssh_user
    port        = self.triggers.ssh_port
    private_key = self.triggers.ssh_private_key
    timeout     = "30s"
  }

  provisioner "file" {
    content     = each.value.content
    destination = "/tmp/mf-${each.key}"
  }

  provisioner "remote-exec" {
    inline = [
      "${each.value.sudo ? "sudo /usr/bin/" : ""}install -m ${each.value.mode} -o ${each.value.owner} -g ${each.value.group} /tmp/mf-${each.key} ${each.value.path}",
      "rm -f /tmp/mf-${each.key}",
      each.value.on_change != "" ? each.value.on_change : ":",
    ]
  }

  provisioner "remote-exec" {
    when       = destroy
    on_failure = continue
    inline     = [self.triggers.on_destroy != "" ? self.triggers.on_destroy : ":"]
  }
}
